/**
 * Detox configuration (Detox 20, Jest runner).
 *
 * The native projects under `ios/` and `android/` are generated by
 * `expo prebuild` (they are gitignored — see ADR 0001). Expo derives the Xcode
 * project/scheme/workspace name from the app `name` ("Users Directory") by
 * stripping non-alphanumerics, i.e. "UsersDirectory". If a future prebuild
 * changes that derivation, confirm the real names post-prebuild with:
 *   ls ios/*.xcworkspace
 *   ls ios/build/Build/Products/Debug-iphonesimulator
 * and reconcile `binaryPath`, `-workspace`, and `-scheme` below.
 *
 * Devices are auto-detected so the config is portable across machines (simulator
 * lists vary by Xcode version; AVD names are arbitrary). Resolution order per
 * platform: env override → first available device → documented fallback. Pin a
 * specific device (or for CI) via `DETOX_IOS_DEVICE` / `DETOX_AVD_NAME`.
 *
 * @type {Detox.DetoxConfig}
 */
const { execSync } = require('child_process');

function sh(cmd) {
  return execSync(cmd, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
}

// iOS: env override → newest available iPhone simulator → documented fallback.
function pickIosDevice() {
  if (process.env.DETOX_IOS_DEVICE) return process.env.DETOX_IOS_DEVICE;
  try {
    const { devices } = JSON.parse(
      sh('xcrun simctl list devices available --json'),
    );
    const iphones = Object.values(devices)
      .flat()
      .filter((d) => d.isAvailable && /^iPhone/.test(d.name))
      .map((d) => d.name);
    // Prefer a plain "iPhone <n>" with the highest generation; else first match.
    const plain = iphones
      .map((n) => [n, /^iPhone (\d+)$/.exec(n)])
      .filter(([, m]) => m)
      .sort((a, b) => Number(a[1][1]) - Number(b[1][1]));
    if (plain.length) return plain[plain.length - 1][0];
    if (iphones.length) return iphones[0];
  } catch {
    /* not macOS / no Xcode — fall through to the documented default */
  }
  return 'iPhone 15';
}

// Android: env override → first installed AVD → documented fallback.
// `emulator` may not be on PATH; also try $ANDROID_HOME/emulator.
function pickAndroidAvd() {
  if (process.env.DETOX_AVD_NAME) return process.env.DETOX_AVD_NAME;
  const candidates = [
    'emulator -list-avds',
    process.env.ANDROID_HOME &&
      `"${process.env.ANDROID_HOME}/emulator/emulator" -list-avds`,
  ].filter(Boolean);
  for (const cmd of candidates) {
    try {
      const avds = sh(cmd)
        .split('\n')
        .map((s) => s.trim())
        .filter(Boolean);
      if (avds.length) return avds[0];
    } catch {
      /* try next candidate */
    }
  }
  return 'Pixel_7_API_34';
}

module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      config: 'e2e/jest.config.js',
    },
    jest: {
      setupTimeout: 180000,
    },
  },
  // NOTE on debug vs release: the `*.debug` apps are Expo **dev-client** builds —
  // they load JS from Metro over the network. Under Detox's cold
  // `launchApp({ newInstance: true })` with no Metro URL, the dev client shows
  // its "enter a URL" launcher and the test hangs. They're kept for the
  // Metro-attached workflow (run `npx expo start --dev-client` first), but the
  // **release** apps are the default E2E path: they embed the JS bundle, so they
  // need no Metro and boot straight into the app — deterministic, as Detox
  // recommends. Expo's generated `android/app/build.gradle` signs release with
  // the debug keystore, so no signing setup is required.
  apps: {
    'ios.debug': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Debug-iphonesimulator/UsersDirectory.app',
      // `-quiet` silences xcodebuild's verbose per-file output; warnings and
      // errors are still printed, so a failed build is still legible.
      build:
        'xcodebuild -quiet -workspace ios/UsersDirectory.xcworkspace -scheme UsersDirectory -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'ios.release': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Release-iphonesimulator/UsersDirectory.app',
      // `-quiet` silences xcodebuild's verbose per-file output; warnings and
      // errors are still printed, so a failed build is still legible.
      build:
        'xcodebuild -quiet -workspace ios/UsersDirectory.xcworkspace -scheme UsersDirectory -configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'android.debug': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      // Scope to the :app module. Unqualified `assembleAndroidTest` also builds
      // androidTest APKs for every Expo library module (:expo, :expo-constants,
      // :expo-log-box, ...) — which Detox never uses and which fail packaging
      // (PackageAndroidArtifact / IncrementalSplitterRunnable). Detox only needs
      // the app's test APK; the libraries are consumed as AARs.
      build:
        'cd android && ./gradlew :app:assembleDebug :app:assembleDebugAndroidTest -DtestBuildType=debug',
    },
    'android.release': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/release/app-release.apk',
      // Same :app scoping rationale as android.debug above. `assembleRelease`
      // also bundles the JS, so the APK is self-contained (no Metro needed).
      build:
        'cd android && ./gradlew :app:assembleRelease :app:assembleReleaseAndroidTest -DtestBuildType=release',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: pickIosDevice(),
      },
    },
    emulator: {
      type: 'android.emulator',
      device: {
        avdName: pickAndroidAvd(),
      },
    },
  },
  configurations: {
    // Default E2E path — self-contained release builds (no Metro).
    'ios.sim.release': {
      device: 'simulator',
      app: 'ios.release',
    },
    'android.emu.release': {
      device: 'emulator',
      app: 'android.release',
    },
    // Metro-attached dev-client builds — run `npx expo start --dev-client` first.
    'ios.sim.debug': {
      device: 'simulator',
      app: 'ios.debug',
    },
    'android.emu.debug': {
      device: 'emulator',
      app: 'android.debug',
    },
  },
};
